version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    environment:
      LD_LIBRARY_PATH=/usr/local/lib
    steps:
      - checkout
      - run: apt-get update -qq
      - run: apt-get install -y -qq odb libodb-dev libodb-sqlite-2.4 libodb-boost-2.4 libsqlite3-dev
      - run: apt-get install -y -qq g++ cmake
      - run: apt-get install -y -qq libboost-all-dev
      - run: apt-get install -y -qq pkg-config
      - run: apt-get install -y -qq libsoprano-dev
      - run: apt-get install -y -qq qt4-default
      - run: apt-get install -y -qq libgeos-dev libgeos++-dev
      - run: apt-get install -y -qq libeigen3-dev
      - run: apt-get install -y -qq git
      - run: apt-get install -y -qq libgeographic-dev
      - run: mkdir build
      - run: cd build && cmake .. && make -j2
      - run: cd build && ctest --output-on-failure


